---
title: "01-lab01-Pre_Class-SM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(webex)
```

# Lab 1

```{block, type="info"}
In this lab we will be introduced to the skills we will develop over the next year and beyond. This lab will introduce open science and why it is relevant to your development as a Psychologist. We will meet our groups and the staff that will be leading our labs and who we will get to know well over these two semesters. We can't wait to get started!
```

## Pre-class activity

### The Reproducibility Crisis 

There is an ongoing debate within Psychology regarding whether the discipline is experiencing a **reproducibility crisis**. When we say **reproducibility** we mean the extent to which **consistent results** are obtained when we repeat an experiment under **comparable conditions**. So, when we say reproducibility **crisis** we mean that efforts to replicate past study findings often do not show the same results. For example, in 2015, a [team of researchers](https://www.nature.com/articles/s41562-018-0399-z) examined social science experiments published in the academic journals _Nature_ and _Science_ between 2010 and 2015. Out of 21 experiments, 13 were successfully replicated. 

**Why is this happening?**

When conducting research, you have to ask yourself a lot of questions: How many participants will I recruit? What variables am I interested in? What's the best way to analyse my data. This is called **researcher degrees of freedom**. This means researchers often have a lot of flexibility and can approach data in a "have a look" manner. Crucially, researcher degrees of freedom can lead to researchers using **questionable research practices** such as: 

* Failing to report all of a study's dependent measures (e.g what you measure in the experiment)
* Collecting more data after peeking at your results in order to make your results significant 
* Failing to report all conditions in a study (e.g. Collecting data from three conditions - no/low/high anxiety - but only reporting two)
* Stopping data collection earlier than planned because you found significant results 
* Rounding off p-values to achieve significance (e.g. reporting p = 0.054 as p = 0.05) 
* Only reporting studies that "worked"
* HARKing - Hypothesising After Results Are Known (e.g. claiming you **predicted** these results before collecting data)

In some cases, researchers have even been known to [falsify](https://www.sciencemag.org/news/2012/09/harvard-psychology-researcher-committed-fraud-us-investigation-concludes) their data. 

**Why should I care?**

Science does not occur in a vacuum. Work that is published and disseminated then goes on to influence public knowledge (e.g. through reporting in the media) and the decisions our politicians make every day.  

**What can be done about it?**

During your time here at Glasgow, we will support you in developing skills and experience in **open science** practices. Open science practices are actions which aim to improve the **transparency**, **accessibility**, and **reproducibility** of scientific research. 

Watch this [video](https://www.youtube.com/watch?v=1rFWeTryiW4&feature=youtu.be) of [Dr Simine Vazire](https://twitter.com/siminevazire?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) talking about open science and why it is an important concept for us to understand in Psychology.  

## Additional resources around open science and reproducibility 

[Is most published research wrong?](https://youtu.be/42QuXLucH3Q)

[Replicability and Reproducibility Debate with Professor Dorothy Bishop](https://www.youtube.com/watch?v=UN8jgyXtz6A)

[Why an Entire Field of Psychology Is in Trouble](https://youtu.be/2MDNvKXdLEM)

[Beyond Cherry-picking](https://socialsciences.nature.com/users/200472-amy-orben/posts/42763-beyond-cherry-picking) by [Amy Orben](https://twitter.com/orbenamy?lang=en)

******

## In Class Activity

```{block, type = "info"}

Building upon what you have learned so far about reproducibility and open science, you will take part in a simple drawing task in groups - following the instructions below. We will then come back together as a class to discuss our attempts!

```

### Activity 1: Replication task  

In your groups please complete these steps on a bit of paper.

*Draw a square

*Draw another square at 15 degree angle to the bottom of the 1st square

*Draw 4 lines down from each corner of the 2nd square

*Draw a circle next to 2nd square

*Draw a smaller circle on top of first circle 

*Draw upward line from side of 1st circle

*Draw 2 triangles on top of 2nd circle

Once you have finished, hand in your attempt to the GTAs.

**Do you notice anything about how these instructions were understood across the class?**

## Activity 2: Getting to know the data

This semester we will use the same dataset each week to develop our skills and knowledge. The dataset is from Woodworth et al. (2018) details of which can be found here [Web-based Positive Psychology Interventions: A Reexamination of Effectiveness](https://openpsychologydata.metajnl.com/articles/10.5334/jopd.35/).

Take some time now to read through the study and familiarise yourself with the data you will be using over the coming weeks.  

******

**Pause and test your knowledge!**

* How many questionnaire variables are in the dataset? 

`r mcq(c(answer = "2", "4", "3"))`

* What does the AHI measure? 

`r fitb(c("Happiness", ignore_case = TRUE))` 

* What does the CES-D measure? 

`r fitb(c("Depression", ignore_case = TRUE))`

******

**In groups, have a think about what a possible research question might look like. How would you use this data? Would you be interested in studying any other variables alongside the data that you have?**



