--- 
title: "Level 1 Data Skills"
author: "psyTeachR"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "ug1-practical-materials"
---

```{r cite-packages, include = FALSE}
# automatically create a bib database for R packages
# add any packages you want to cite here
knitr::write_bib(c(
  .packages(), 'bookdown', 'tidyverse'
), 'packages.bib')

```

# Overview {-}

This resource outlines the structure and content of our level 1 practical course at the School of Psychology at the University of Glasgow. We have developed these with a few key principles in mind:

1. **A mixed-format approach to skill development involving independent study, in-class activities, and individualized assessment.** Each practical class, which we call 'labs' in the student's timetable and in this book, has prep material for the students to read and work through independently before class to provide context and additional support for the the in-class activities. These can take the form of, for example, videos made by the course lead informally talking through the tasks while live coding, papers related to the data being used, or lectures related to the topic of the lab. These prep and in-class activities are closely linked to the assessments to enable skills to develop through practice. We also hold drop in practice sessions twice a week where Graduate Teaching Assistants (GTAs) are present to guide students to prep and in-class activites that will help in assessment completion while taking a "hands-off the keyboard" approach.   

2. **Cumulative skill development across labs.** Assessments enable students to demonstrate the development of their coding and data analysis skills. 
However, we take the perspective of skills develop through practice therefore each assessment builds on the work not only completed in the associated lab but provides an opportunity to demonstrate skill acquisition of skills learnt to date over the previous labs. Students will have received the solution for the previously attempted lab as a minimum, grade and feedback as well as the solution if feedback and grade turnaround permits, so this is an excellent opportunity for them to demonstrate integration of feedback and related skill development.

3. **Modeling good practice using live coding.** Live coding is an important part of our teaching. We structure our classes with a staff member leading with support from two Graduate Teaching Assistants (GTAs). This enables the staff member to lead the class through the content while the GTAs can ensure the individual students are being challenged and supported adequately. The structure of skill building over labs supports this mode of teaching with the focus being on what each component of the code enables us to do rather than memorising code. Additional lab activites, such as the building of a portfolio over each semester, aims to encourage our students to focus on the understanding of the aim of the task the obtaining the code rather than memorising code only. The code that you see in the following chapters is the code staff were advised to use when live coding in class. Students were asked to open up a script and then staff live coded whilst talking through each task with GTA support ensuring students were confidently on task.

**The overall goals for our students in our year 1 Psychology labs are:**

* To understand the current state of psychological science and what Open Science is as well as its importance

* To be clear on the importance of being confident and competent in data management

* Develop skills in using RStudio as a tool for authoring R scripts and dynamic reports in RMarkdown

* Develop basic skills in R + tidyverse for data import, data wrangling, and visualization

```{block, type="info"}
We have not shared the assessments for the labs but they are closely related to the in-class activities so these can be used as assessment templates too with code remaining similar to in-class but data or variables of interest changing. Where we have had formative or optional tasks for students to complete these will be listed under post-lab activities.

You may notice a progression between labs 1 to 4 and labs 5 to 8. This is due to labs 1 to 4 building on skills progressively with associated increase in assessment weighting whilst labs 5 to 8 have a more consistent yet higher weighting. 
```
